require('dotenv').config();
const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const authRoutes = require('./routes/auth');
const templateRoutes = require('./routes/templates');
const app = express();
app.use(cors());
app.use(express.json());
connectDB(process.env.MONGO_URI);
app.use('/api/auth', authRoutes);
app.use('/api/templates', templateRoutes);
app.get('/', (req, res) => res.json({ ok: true }));
app.listen(process.env.PORT || 5000, () => console.log('Server started'));
